### ISSUE TITLE
test_rule_fail failes because of passed tests.

### ISSUE THREAD

**Issue by nomisge** [jwbargsten/pytest-archon#35] opened 2024-05-01 21:50 UTC
If I run tests, I get following Fail:

```
FAILED tests/test_pytest_fixture.py::test_rule_fail - AssertionError: assert {'passed': 2, 'skipped': 0, 'failed': 1, 'errors': 0, 'xpassed': 0, 'xfailed': 0} == {'passed': 0, 'skipped': 0, 'failed': 1, 'errors': 0, 'xpassed': 0, 'xfailed': 0}
```

Within the testfile ```assert_outcomes(failed=1)``` is called, which should correctly assert True. I guess the issue is, that the standard value for the parameter ```passed``` is 0.  And the whole thing asserts False, at least on my system.

If the test works on other system, could it be, that some pytest plugin generates passed tests on my system, that aren't there on other systems without that plugin?

Maybe a solution would be to use ```parseoutcomes()``` instead and assert on failed entry of the returned dictionary only?

**Comment by jwbargsten** [comment] 2024-05-02 05:55
That is indeed a strange error. I'm a bit hesitant to modify this code, because we follow [the official pytest documentation](https://github.com/pytest-dev/pytest/blob/main/CONTRIBUTING.rst#writing-tests).

Basically something is running additional tests on your machine. Let's assume one of these tests fail, how should we know that it was our test that should have failed?

You could try to set up a clean, isolated virtualenv and re-run the tests.

**Comment by jwbargsten** [comment] 2024-05-07 20:46
I'll close this issue. If you think you found a bug, try to build a reproducible example and we can re-open this issue again!

**Closed as completed by jwbargsten** 2024-05-07 20:46 UTC
